name: handyman_provider
description: Handyman provider project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  material_color_generator: ^1.1.0
  flutter_screenutil: ^5.6.1
  loggy: ^2.0.3
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  stacked: ^3.1.0+3
  get_it: ^7.2.0
  flutter_easyloading: ^3.0.5
  google_fonts: ^4.0.3
  icons_plus: ^4.0.0
  string_validator: ^0.3.0
  water_drop_nav_bar: ^2.2.0+5
  cached_network_image: ^3.2.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  google_maps_flutter: ^2.2.3
  open_filex: ^4.3.2
  path: ^1.8.3
  path_provider: ^2.0.12
  url_launcher: ^6.1.9
  timelines: ^0.1.0
  file_picker: ^5.2.5
  pinput: ^2.2.30
#  google_maps_place_picker_mb: ^3.0.1
  multi_select_flutter: ^4.1.3
  smooth_star_rating_null_safety: ^1.0.4+2
#  location_picker_flutter_map: ^1.2.0
  flutter_place_picker: ^0.0.1-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  icons_launcher: ^2.1.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

dependency_overrides:
  path: ^1.8.3

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - google_fonts/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: google_fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: google_fonts/SourceSansPro-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: google_fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: google_fonts/SourceSansPro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: google_fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/SourceSansPro-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: google_fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: google_fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: google_fonts/SourceSansPro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: google_fonts/SourceSansPro-Regular.ttf
        - asset: google_fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: google_fonts/SourceSansPro-SemiBoldItalic.ttf
          style: italic
          weight: 600